/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Home assistant IP:": {                          "en": "Home assistant IP:",                              "de": "IP-Adresse des Heimassistenten:",                 "ru": "Домашний помощник IP:",                           "pt": "IP do assistente doméstico:",                     "nl": "Thuisassistent IP:",                              "fr": "IP de l'assistant à domicile :",                  "it": "IP assistente domestico:",                        "es": "IP del asistente de hogar:",                      "pl": "Adres IP asystenta domowego:",                    "zh-cn": "家庭助理IP："},
    "Home assistant WS Port:": {                     "en": "Home assistant WS Port:",                         "de": "Home Assistant WS-Port:",                         "ru": "Домашний помощник WS Порт:",                      "pt": "Assistente doméstico Porta WS:",                  "nl": "Thuisassistent WS Poort:",                        "fr": "Port WS de l'assistant domestique :",             "it": "Porta WS dell'assistente domestico:",             "es": "Asistente doméstico Puerto WS:",                  "pl": "Asystent domowy Port WS:",                        "zh-cn": "家庭助理 WS 端口："},
    "Password repeat:": {                            "en": "Password repeat:",                                "de": "Passwort wiederholen:",                           "ru": "Повтор пароля:",                                  "pt": "Repetição de senha:",                             "nl": "Wachtwoord herhalen:",                            "fr": "Répéter le mot de passe :",                       "it": "Ripeti password:",                                "es": "Repite la contraseña:",                           "pl": "Powtórz hasło:",                                  "zh-cn": "密码重复："},
    "Password:": {                                   "en": "Password:",                                       "de": "Passwort:",                                       "ru": "Пароль:",                                         "pt": "Senha:",                                          "nl": "Wachtwoord:",                                     "fr": "Mot de passe:",                                   "it": "Parola d'ordine:",                                "es": "Clave:",                                          "pl": "Hasło:",                                          "zh-cn": "密码："},
    "Passwords missmatch!": {                        "en": "Passwords missmatch!",                            "de": "Passwörter stimmen nicht überein!",               "ru": "Пароли не совпадают!",                            "pt": "As senhas não correspondem!",                     "nl": "Wachtwoorden komen niet overeen!",                "fr": "Les mots de passe ne correspondent pas !",        "it": "Le password non corrispondono!",                  "es": "¡Las contraseñas no coinciden!",                  "pl": "Niezgodność haseł!",                              "zh-cn": "密码不匹配！"},
    "Secure:": {                                     "en": "HTTPS?:",                                         "de": "HTTPS?:",                                         "ru": "HTTPS?:",                                         "pt": "HTTPS?:",                                         "nl": "HTTPS?:",                                         "fr": "HTTPS ? :",                                       "it": "HTTPS?:",                                         "es": "¿HTTPS?:",                                        "pl": "HTTPS?:",                                         "zh-cn": "HTTPS？："},
};