/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "FHEM Telnet IP:": {                             "en": "FHEM Telnet IP:",                                 "de": "FHEM Telnet IP:",                                 "ru": "FHEM Telnet IP:",                                 "pt": "FHEM Telnet IP:",                                 "nl": "FHEM Telnet-IP:",                                 "fr": "IP Telnet FHEM :",                                "it": "IP Telnet FHEM:",                                 "es": "FHEM Telnet IP:",                                 "pl": "Adres IP Telnetu FHEM:",                          "zh-cn": "FHEM 远程登录 IP："},
    "FHEM Telnet Port:": {                           "en": "FHEM Telnet Port:",                               "de": "FHEM Telnet Port:",                               "ru": "FHEM Telnet порт:",                               "pt": "Porta Telnet FHEM:",                              "nl": "FHEM Telnet-poort:",                              "fr": "Port Telnet FHEM :",                              "it": "Porta Telnet FHEM:",                              "es": "Puerto Telnet FHEM:",                             "pl": "Port Telnet FHEM:",                               "zh-cn": "FHEM 远程登录端口："},
    "FHEM adapter settings": {                       "en": "FHEM adapter settings",                           "de": "FHEM Adapter Einstellungen",                      "ru": "Настройки драйвера FHEM",                         "pt": "Configurações do adaptador FHEM",                 "nl": "Instellingen FHEM-adapter",                       "fr": "Paramètres de l'adaptateur FHEM",                 "it": "Impostazioni dell'adattatore FHEM",               "es": "Configuración del adaptador FHEM",                "pl": "Ustawienia adaptera FHEM",                        "zh-cn": "FHEM 适配器设置"},
    "Password repeat:": {                            "en": "Password repeat:",                                "de": "Kennwort-Woederholung:",                          "ru": "Подтверждение пароля:",                           "pt": "Repetição de senha:",                             "nl": "Wachtwoord herhalen:",                            "fr": "Répéter le mot de passe :",                       "it": "Ripeti password:",                                "es": "Repite la contraseña:",                           "pl": "Powtórz hasło:",                                  "zh-cn": "密码重复："},
    "Password:": {                                   "en": "Password:",                                       "de": "Kennwort:",                                       "ru": "Пароль:",                                         "pt": "Senha:",                                          "nl": "Wachtwoord:",                                     "fr": "Mot de passe:",                                   "it": "Parola d'ordine:",                                "es": "Clave:",                                          "pl": "Hasło:",                                          "zh-cn": "密码："},
    "Passwords missmatch!": {                        "en": "Passwords missmatch!",                            "de": "Kennworte sind unterschiedlich!",                 "ru": "Пароли не совпадают!",                            "pt": "As senhas não correspondem!",                     "nl": "Wachtwoorden komen niet overeen!",                "fr": "Les mots de passe ne correspondent pas !",        "it": "Le password non corrispondono!",                  "es": "¡Las contraseñas no coinciden!",                  "pl": "Niezgodność haseł!",                              "zh-cn": "密码不匹配！"},
    "Prompt:": {                                     "en": "Prompt:",                                         "de": "Prompt:",                                         "ru": "Промпт:",                                         "pt": "Pronto:",                                         "nl": "Snel:",                                           "fr": "Rapide:",                                         "it": "Richiesta:",                                      "es": "Inmediato:",                                      "pl": "Podpowiedź:",                                     "zh-cn": "迅速的："},
    "tooltip_password": {                            "en": "Optional. Only if FHEM requires password.",       "de": "Optional. Nur falls in FHEM konfiguriert",        "ru": "Не обязательно. Только если настроено в FHEM",    "pt": "Opcional. ",                                      "nl": "Optioneel. ",                                     "fr": "Optionnel. ",                                     "it": "Opzionale. ",                                     "es": "Opcional. ",                                      "pl": "Opcjonalny. ",                                    "zh-cn": "可选的。"},
    "tooltip_prompt": {                              "en": "You can change standard prompt from 'hass>' to something else.", "de": "Man kann hier ein eigenes Prompt setzen. Default ist 'hass>'", "ru": "Можно задать собственный промпт. По умолчанию 'hass>'", "pt": "Você pode alterar o prompt padrão de 'hass>' para outra coisa.", "nl": "U kunt de standaardprompt wijzigen van 'hass>' naar iets anders.", "fr": "Vous pouvez changer l'invite standard de 'hass>' en quelque chose d'autre.", "it": "Puoi cambiare il prompt standard da 'hass>' a qualcos'altro.", "es": "Puede cambiar el aviso estándar de 'hass>' a otra cosa.", "pl": "Możesz zmienić standardowy monit z „hass>” na coś innego.", "zh-cn": "您可以将标准提示从“hass>”更改为其他内容。"},
};